FROM alembic

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get clean && rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get update
RUN apt-get update && apt-get install -y python-pip jupyter-notebook libsm6 libxext6 libxrender-dev

RUN pip install --upgrade pip
RUN python -m pip install ipykernel matplotlib opencv-python==4.2.0.32
RUN python -m ipykernel install --user

CMD ["jupyter", "notebook", "--port=8899", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
